services:
  lightmirrors:
    image: lightmirrors/mirrors
    build:
      context: ./src
    volumes:
      - ./src/:/app
      - ./data/cache:/app/cache
      - ./data/metrics:/app/data
    env_file:
      - .env
    environment:
      - SSL_SELF_SIGNED=false
      - SERVER_PORT=8080
      # 缓存生命周期管理配置
      - CACHE_EXPIRY_DAYS=30              # 缓存过期天数（默认30天）
      - ENABLE_CACHE_CLEANUP=true         # 是否启用自动清理（默认true）
      # 会话管理配置
      - SESSION_TIMEOUT=5                 # 会话超时时间（秒，默认5秒）
      - ENABLE_SESSION_SUMMARY=true       # 是否启用会话汇总（默认true）
    networks:
      - app
    restart: unless-stopped
    # for linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:8080:8080"
  aria2:
    image: lightmirrors/aria2
    build: ./aria2
    volumes:
      - ./aria2/aria2.conf:/aria2.conf
      - ./data/cache:/app/cache
      - ./data/aria2:/data/
    networks:
      - app
    env_file:
      - .env
    restart: unless-stopped
networks:
  app:
    name: lightmirrors_app
    driver: bridge